/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcc_app5_TCPUtils */

#ifndef _Included_com_xcc_app5_TCPUtils
#define _Included_com_xcc_app5_TCPUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcc_app5_TCPUtils
 * Method:    connectServe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app5_TCPUtils_connectServe
  (JNIEnv *, jclass);

/*
 * Class:     com_xcc_app5_TCPUtils
 * Method:    startServe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app5_TCPUtils_startServe
  (JNIEnv *, jclass);

/*
 * Class:     com_xcc_app5_TCPUtils
 * Method:    stopServe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app5_TCPUtils_stopServe
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
