/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcc_app3_MyJni3 */

#ifndef _Included_com_xcc_app3_MyJni3
#define _Included_com_xcc_app3_MyJni3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcc_app3_MyJni3
 * Method:    fileW
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app3_MyJni3_fileW
  (JNIEnv *, jclass);

/*
 * Class:     com_xcc_app3_MyJni3
 * Method:    fileR
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xcc_app3_MyJni3_fileR
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
