/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcc_app3_MyJni */

#ifndef _Included_com_xcc_app3_MyJni
#define _Included_com_xcc_app3_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcc_app3_MyJni
 * Method:    fileW
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app3_MyJni_fileW
  (JNIEnv *, jclass);

/*
 * Class:     com_xcc_app3_MyJni
 * Method:    fileR
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_xcc_app3_MyJni_fileR
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
