/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcc_app6_UDPUtils */

#ifndef _Included_com_xcc_app6_UDPUtils
#define _Included_com_xcc_app6_UDPUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcc_app6_UDPUtils
 * Method:    connectServe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app6_UDPUtils_connectServe
  (JNIEnv *, jclass);

/*
 * Class:     com_xcc_app6_UDPUtils
 * Method:    startServe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app6_UDPUtils_startServe
  (JNIEnv *, jclass);

/*
 * Class:     com_xcc_app6_UDPUtils
 * Method:    stopServe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app6_UDPUtils_stopServe
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
