/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcc_app2_XccLibs */

#ifndef _Included_com_xcc_app2_XccLibs
#define _Included_com_xcc_app2_XccLibs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcc_app2_XccLibs
 * Method:    cRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app2_XccLibs_cRun
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
