/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcc_app4_MyJniThread */

#ifndef _Included_com_xcc_app4_MyJniThread
#define _Included_com_xcc_app4_MyJniThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcc_app4_MyJniThread
 * Method:    startThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app4_MyJniThread_startThread
  (JNIEnv *, jclass);

/*
 * Class:     com_xcc_app4_MyJniThread
 * Method:    stopThread
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_xcc_app4_MyJniThread_stopThread
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
