/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcc_app4_MyJniThread2 */

#ifndef _Included_com_xcc_app4_MyJniThread2
#define _Included_com_xcc_app4_MyJniThread2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcc_app4_MyJniThread2
 * Method:    startThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app4_MyJniThread2_startThread
  (JNIEnv *, jclass);

/*
 * Class:     com_xcc_app4_MyJniThread2
 * Method:    stopThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xcc_app4_MyJniThread2_startThread2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
