/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcc_ndkstudy_GetString */

#ifndef _Included_com_xcc_ndkstudy_GetString
#define _Included_com_xcc_ndkstudy_GetString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcc_ndkstudy_GetString
 * Method:    stringToJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xcc_ndkstudy_GetString_stringToJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
